# Generated by Django 3.0.3 on 2020-04-05 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=141)),
                ('a_photo', models.ImageField(blank=True, upload_to='About/%Y/%m/%d/')),
                ('a_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('a_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=155)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_phone', models.CharField(max_length=150)),
                ('c_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('p_title', models.CharField(max_length=200)),
                ('p_subtitle', models.CharField(max_length=200)),
                ('p_photo', models.ImageField(blank=True, upload_to='portfolio/%Y/%m/%d/')),
                ('p_conent', models.TextField(blank=True)),
                ('used_technology', models.TextField(blank=True)),
                ('p_client', models.CharField(max_length=200)),
                ('p_category', models.CharField(max_length=200)),
                ('p_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=150)),
                ('s_content', models.TextField()),
                ('s_photo', models.ImageField(blank=True, upload_to='Service/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=155)),
                ('member_photo', models.ImageField(blank=True, upload_to='Team/%Y/%m/%d/')),
                ('member_deg', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=152)),
                ('fb', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=151)),
            ],
        ),
    ]
